module.exports = {
// SERVER => CLIENT
REQUESTED_BLOCK : "REQUESTED_BLOCK",
REQUESTED_CHAIN : "REQUESTED_CHAIN",
BLOCK_MINE_RESPONSE : "BLOCK_MINE_RESPONSE",
PEERS_RESPONSE : "PEERS_RESPONSE",

// CLIENT => SERVER
GET_BLOCK_BY_HASH : "GET_BLOCK_BY_HASH",
GET_FULL_CHAIN : "GET_FULL_CHAIN",
BLOCK_MINED : "BLOCK_MINED",
GET_PEERS : "GET_PEERS",
NEW_TRANSACTION : "NEW_TRANSACTION",
}

